# Generated by Django 6.0.4 on 2026-04-08 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('description', models.CharField(max_length=100)),
                ('current_price', models.DecimalField(decimal_places=10, max_digits=10)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=30)),
                ('market_cap_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('price_change_24h', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('price_change_percentage_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptos.crypto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'crypto')},
            },
        ),
        migrations.CreateModel(
            name='CryptoPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='cryptos.crypto')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('crypto', 'timestamp')},
            },
        ),
    ]
